name: CI Pipeline

on: [push] # Executa a cada push no repositório

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Baixa o código do repositório
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install flask coverage

      - name: Run Tests with Coverage
        run: python -m coverage run -m unittest -v tests/appTest.py

      - name: Generate Coverage Report
        run: python -m coverage report
  
  deploy-prod-job:
    runs-on: ubuntu-latest
    environment: production        # Ativa a necessidade de aprovação manual
    steps:
      - name: Starting deployment
        run: echo "Deploying branch ${{ github.ref_name }} to production..." 
        
      - name: Simulate deployment time
        run: sleep 20 # Simulates a 20-second process
        
      - name: Conclusion
        run: echo "Deployment completed successfully!" 